/* Telink B91 memory layout */
MEMORY
{
    /* B91: 512KB Flash, 256KB SRAM */
    FLASH : ORIGIN = 0x20000000, LENGTH = 512K
    RAM   : ORIGIN = 0x00000000, LENGTH = 256K
}

/* Region aliases required by riscv-rt v0.13 link.x */
REGION_ALIAS("REGION_TEXT", FLASH);
REGION_ALIAS("REGION_RODATA", FLASH);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_HEAP", RAM);
REGION_ALIAS("REGION_STACK", RAM);
