[package]
name = "nrf52840-mdk-usb-dongle"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Physical wiring for the Makerdiary nRF52840 MDK USB Dongle"
repository = "https://github.com/faronov/zigbee-rs"
publish = false

[workspace]

[dependencies]
embassy-nrf = { version = "0.3", features = ["nrf52840"] }
