[package]
name = "bl702-hal"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Pure-Rust BL702 peripheral support"
repository = "https://github.com/faronov/zigbee-rs"
publish = false

[dependencies]
embedded-hal = "1.0"
embedded-storage = "0.3"

[target.'cfg(target_arch = "riscv32")'.dependencies]
riscv = { version = "0.15", features = ["critical-section-single-hart"] }
