//! Low-level ESP32 802.15.4 radio driver wrapper.
//!
//! Provides TX with completion signaling and polling-based RX on top of
//! `esp-radio::ieee802154`.
//!
//! # Hardware ACK policy (important)
//!
//! IEEE 802.15.4 acknowledgements on the ESP32-C6/H2 are generated by the
//! radio hardware, not by software: the ACK has to leave the antenna
//! `aTurnaroundTime` (192 µs) after the end of the received frame, which no
//! polling loop can meet.
//!
//! Two hardware conditions must both hold for the radio to emit an ACK:
//!
//! 1. `hw_auto_ack_tx_en` must be set — that is `Config::auto_ack_tx`.
//!    `Config::default()` leaves it `false`, and `Ieee802154::set_config()`
//!    overwrites the `true` value that `ieee802154_pib_init()` installed, so a
//!    driver that just passes `Config::default()` never acknowledges anything.
//! 2. Promiscuous mode must be **off** and the hardware address filter must be
//!    programmed (PAN ID, short address, extended address). Espressif couples
//!    the two explicitly — `esp_ieee802154_set_promiscuous()` in ESP-IDF does
//!    `pib_set_auto_ack_rx(!enable)` / `pib_set_auto_ack_tx(!enable)` — because
//!    a sniffing radio must not acknowledge other people's frames.
//!
//! [`Ieee802154Driver`] therefore owns the ACK policy: promiscuous mode is only
//! entered for scanning, and enabling it automatically disables auto-ACK TX
//! exactly like ESP-IDF does.
//!
//! ACK *reception* is handled in software. `esp-radio` 0.17 handles
//! `Event::AckRxDone` with a `trace!()` and never queues the frame, so
//! `auto_ack_rx = true` would hide the acknowledgement (and its frame-pending
//! bit) completely and add an `RxAckTimeout` stall to every unacknowledged
//! transmission. With `auto_ack_rx = false` the incoming ACK is instead
//! delivered like any other frame through the normal `RxDone` path — verified
//! on an ESP32-C6 devkit, see [`Ieee802154Driver::ack_observed`] — so
//! [`Ieee802154Driver::transmit_with_ack`] can confirm deliveries itself.

use core::sync::atomic::{AtomicBool, Ordering};

use esp_radio::ieee802154::{Config, Error, Ieee802154};

/// TX completion flag — set by ISR callback, cleared before TX.
static TX_COMPLETE: AtomicBool = AtomicBool::new(false);

/// TX-done callback — called from radio ISR when TX finishes.
fn on_tx_done() {
    TX_COMPLETE.store(true, Ordering::Release);
}

/// Received frame data (copied out of radio buffer).
pub struct RxFrame {
    pub data: [u8; 127],
    pub len: usize,
    pub lqi: u8,
    pub rssi: i8,
}

/// Outcome of a transmission that requested an IEEE 802.15.4 acknowledgement.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TxAckResult {
    /// The matching ACK frame was seen.
    Acked,
    /// The frame went out but no ACK frame was observed.
    NotObserved,
    /// The frame went out but the ACK could not be looked for, because doing so
    /// would have meant dropping already received frames. Treated as sent: a
    /// retransmission would duplicate a frame the peer most likely has.
    NotChecked,
    /// The frame could not be handed to the radio at all.
    TxFailed,
}

/// How many frames may be held while looking for an ACK.
///
/// Deliberately small. Parked frames are invisible to the stack until the MAC
/// polls again, so a deep queue just delivers stale frames; when it is full the
/// driver stops inspecting the radio queue instead of dropping anything (see
/// [`TxAckResult::NotChecked`]).
const PENDING_RX_DEPTH: usize = 4;

/// Wrapper around the ESP32 ieee802154 radio peripheral.
pub struct Ieee802154Driver<'a> {
    driver: Ieee802154<'a>,
    config: Config,
    /// Frames pulled out of the radio queue while sniffing for an ACK. They
    /// must not be dropped: they are ordinary frames for the stack.
    pending: heapless::Deque<RxFrame, PENDING_RX_DEPTH>,
    /// True once an ACK frame has ever been delivered by the radio.
    ack_observed: bool,
    /// Number of frames dropped because [`Self::pending`] was full.
    pending_overflow: u32,
    /// Whether the receiver has been armed at least once since the last
    /// configuration change.
    rx_armed: bool,
}

impl<'a> Ieee802154Driver<'a> {
    pub fn new(mut ieee802154: Ieee802154<'a>, mut config: Config) -> Self {
        apply_radio_policy(&mut config);
        ieee802154.set_config(config);
        // Register TX-done callback for completion signaling
        ieee802154.set_tx_done_callback_fn(on_tx_done);
        log::info!(
            "[ESP RADIO] ch={} promisc={} auto_ack_tx={} auto_ack_rx={} rx_when_idle={} \
             pan={:04X?} short={:04X?} ext={:016X?}",
            config.channel,
            config.promiscuous,
            config.auto_ack_tx,
            config.auto_ack_rx,
            config.rx_when_idle,
            config.pan_id,
            config.short_addr,
            config.ext_addr
        );
        let mut this = Self {
            driver: ieee802154,
            config,
            pending: heapless::Deque::new(),
            ack_observed: false,
            pending_overflow: 0,
            rx_armed: false,
        };
        this.rearm_receive();
        this
    }

    /// Update radio configuration (channel, PAN ID, short address, etc.)
    ///
    /// `set_config()` only updates esp-radio's software PIB; the registers are
    /// written by `ieee802154_pib_update()`, which runs from `rx_init()` and
    /// `tx_init()` only. `rx_init()` is reached from `start_receive()` when the
    /// driver is not already receiving, and `tx_init()` runs before every
    /// transmission, so a changed channel/address is guaranteed to be live by
    /// the time we transmit again.
    pub fn update_config(&mut self, update_fn: impl FnOnce(&mut Config)) {
        let before = self.config;
        update_fn(&mut self.config);
        apply_radio_policy(&mut self.config);
        if before == self.config {
            return;
        }
        self.driver.set_config(self.config);
        // Hard re-arm so `rx_init()` pushes the new PIB into the registers.
        self.rearm_receive();
    }

    /// Enter/leave promiscuous mode, following ESP-IDF semantics: promiscuous
    /// mode disables hardware auto-ACK.
    pub fn set_promiscuous(&mut self, enable: bool) {
        self.update_config(|cfg| cfg.promiscuous = enable);
    }

    /// Program the hardware address filter. All three values must match what
    /// the stack puts into outgoing frames, otherwise the radio drops frames
    /// addressed to us (and never auto-ACKs them).
    ///
    /// `ext` is the on-air (little-endian) EUI-64 byte order, exactly as the
    /// MAC writes it into the addressing fields.
    pub fn set_addresses(&mut self, pan_id: u16, short_addr: u16, ext: &[u8; 8]) {
        let ext_be = u64::from_be_bytes(*ext);
        self.update_config(|cfg| {
            cfg.pan_id = Some(pan_id);
            cfg.short_addr = Some(short_addr);
            cfg.ext_addr = Some(ext_be);
        });
    }

    /// True once the radio has ever handed us an ACK frame.
    pub fn ack_observed(&self) -> bool {
        self.ack_observed
    }

    /// Transmit a raw 802.15.4 frame and wait for TX completion.
    ///
    /// The ESP32 802.15.4 hardware interprets PHR as total OTA length
    /// INCLUDING FCS. We add +2 padding so the full frame is transmitted.
    /// Uses TX-done callback for precise completion detection (~500µs typical).
    pub fn transmit(&mut self, frame: &[u8]) -> Result<(), Error> {
        let mut padded = [0u8; 129];
        padded[..frame.len()].copy_from_slice(frame);

        // Clear TX-done flag before starting TX
        TX_COMPLETE.store(false, Ordering::Release);

        self.driver.transmit_raw(&padded[..frame.len() + 2])?;

        // Wait for TX completion via ISR callback (max 10ms safety timeout)
        let start = esp_hal::time::Instant::now();
        let mut timed_out = false;
        while !TX_COMPLETE.load(Ordering::Acquire) {
            if start.elapsed() > esp_hal::time::Duration::from_millis(10) {
                timed_out = true;
                break; // Safety timeout — TX should never take this long
            }
            core::hint::spin_loop();
        }

        if timed_out {
            // The radio is stuck in `Transmit`; esp-radio's abort handlers only
            // clear status bits and never re-arm, so force RX back on.
            log::warn!("[ESP TX] no TX-done within 10ms, forcing RX re-arm");
            self.rearm_receive();
        }
        // On the normal path the ISR already put us back into RX
        // (`rx_when_idle`), so nothing to do — and calling `start_receive()`
        // here could abort an ACK we are transmitting for a frame that arrived
        // in the meantime.

        Ok(())
    }

    /// Transmit a frame that requested an acknowledgement and wait for the ACK.
    ///
    /// Frames that arrive in the ACK window and are *not* the ACK are parked
    /// instead of being thrown away: the original implementation discarded
    /// them, which silently ate frames the parent sent right after
    /// acknowledging our poll. [`Self::poll_receive`] hands them to the MAC in
    /// arrival order before touching the radio queue again.
    ///
    /// If there is no room left to park, the ACK is *not* looked for. Frames
    /// then stay in the esp-radio queue where they are safe, and the caller is
    /// told the transmission could not be verified rather than being pushed
    /// into a retransmission it does not need. This matters on a busy network:
    /// every broadcast this node sends comes back from a dozen routers within a
    /// few milliseconds.
    pub fn transmit_with_ack(&mut self, frame: &[u8], seq: u8) -> TxAckResult {
        if self.transmit(frame).is_err() {
            return TxAckResult::TxFailed;
        }
        if self.pending.is_full() {
            return TxAckResult::NotChecked;
        }

        // ACK window: aTurnaroundTime (192µs) + ACK duration (352µs) + margin
        // for the ISR that queues it. Kept tight so a genuinely lost frame is
        // retried quickly.
        let deadline = esp_hal::time::Instant::now() + esp_hal::time::Duration::from_micros(1_000);

        while esp_hal::time::Instant::now() < deadline {
            match self.take_from_radio() {
                Some(rx) => {
                    if let Some(ack_seq) = ack_sequence(&rx) {
                        self.note_ack_visible();
                        if ack_seq == seq {
                            return TxAckResult::Acked;
                        }
                        continue;
                    }
                    self.park(rx);
                    if self.pending.is_full() {
                        return TxAckResult::NotChecked;
                    }
                }
                // Don't spin on raw_received(): every call re-issues the RX
                // start command, and restarting RX on top of an inbound
                // preamble is how frames get lost.
                None => spin_micros(50),
            }
        }

        TxAckResult::NotObserved
    }

    /// Ensure the receiver is armed.
    ///
    /// This is deliberately **not** an unconditional re-arm. esp-radio's
    /// `ieee802154_receive()` runs `rx_init()` whenever the driver is not
    /// already in the `Receive` state, and `rx_init()` starts with
    /// `stop_current_operation()` (a `Command::Stop`). After a frame that
    /// requires an acknowledgement the driver state is `TxAck` while the radio
    /// is *transmitting the ACK*, so an unconditional re-arm from an RX polling
    /// loop aborts our own acknowledgement — the exact failure mode this driver
    /// exists to fix.
    ///
    /// With `rx_when_idle = true` the ISR re-arms RX after every RX, TX and ACK
    /// (`next_operation_inner()`), and every [`Self::poll_receive`] call goes
    /// through `raw_received()` → `ensure_receive_enabled()`, which re-issues
    /// `Command::RxStart` after a hardware RX abort (CRC error, filter
    /// mismatch, unexpected ACK). So the only arm that has to happen here is
    /// the first one.
    pub fn start_receive(&mut self) {
        if !self.rx_armed {
            self.rearm_receive();
        }
    }

    /// Unconditional re-arm — only for init, config changes and TX recovery.
    fn rearm_receive(&mut self) {
        self.driver.start_receive();
        self.rx_armed = true;
    }

    /// Poll for a received frame. Returns None if nothing available yet.
    ///
    /// Frames parked during an ACK window are delivered first so the MAC still
    /// sees them in arrival order. ACK frames are handed out too — a sleepy end
    /// device reads its "frame pending" bit to decide whether the parent has
    /// data buffered for it — but they are recorded here as proof that this
    /// platform surfaces acknowledgements at all.
    pub fn poll_receive(&mut self) -> Option<Result<RxFrame, Error>> {
        if let Some(frame) = self.pending.pop_front() {
            return Some(Ok(frame));
        }
        let rx = self.take_from_radio()?;
        if ack_sequence(&rx).is_some() {
            self.note_ack_visible();
        }
        Some(Ok(rx))
    }

    fn note_ack_visible(&mut self) {
        if !self.ack_observed {
            self.ack_observed = true;
            log::info!("[ESP RX] ACK frames are visible to software — ACK tracking enabled");
        }
    }

    /// Pop one frame out of the esp-radio RX queue and normalise it.
    ///
    /// Calling `raw_received()` also re-arms the receiver inside esp-radio
    /// (`ensure_receive_enabled()`), which is what keeps RX alive after a
    /// hardware RX abort (CRC error, filter mismatch, unexpected ACK), so this
    /// is deliberately called even when the queue turns out to be empty.
    fn take_from_radio(&mut self) -> Option<RxFrame> {
        let raw = self.driver.raw_received()?;
        // raw.data[0] is the PHR: MAC frame length including the 2 FCS bytes.
        // The radio overwrites the FCS with RSSI (at len-1) and LQI (at len).
        let phr = (raw.data[0] & 0x7F) as usize;
        if phr < 3 || phr >= raw.data.len() {
            return None;
        }
        let mac_len = (phr - 2).min(125);
        let mut rx = RxFrame {
            data: [0u8; 127],
            len: mac_len,
            lqi: raw.data[phr],
            rssi: raw.data[phr - 1] as i8,
        };
        if mac_len > 0 {
            rx.data[..mac_len].copy_from_slice(&raw.data[1..][..mac_len]);
        }
        Some(rx)
    }

    fn park(&mut self, frame: RxFrame) {
        if self.pending.push_back(frame).is_err() {
            // Should be unreachable: the ACK window stops as soon as the queue
            // is full precisely so that no received frame is ever dropped.
            self.pending_overflow = self.pending_overflow.wrapping_add(1);
            log::warn!(
                "[ESP RX] parking queue overflow, frame dropped (total {})",
                self.pending_overflow
            );
        }
    }
}

/// Busy-wait for approximately `us` microseconds.
fn spin_micros(us: u64) {
    let deadline = esp_hal::time::Instant::now() + esp_hal::time::Duration::from_micros(us);
    while esp_hal::time::Instant::now() < deadline {
        core::hint::spin_loop();
    }
}

/// Force the settings the Zigbee MAC depends on, whatever the caller passed in.
fn apply_radio_policy(cfg: &mut Config) {
    // Hardware auto-ACK TX: mandatory outside promiscuous mode, forbidden
    // inside it (mirrors esp_ieee802154_set_promiscuous()).
    cfg.auto_ack_tx = !cfg.promiscuous;
    // Hardware ACK *reception* is useless on esp-radio 0.17: `Event::AckRxDone`
    // is only `trace!()`ed, the frame is never queued, and a pending TX would
    // instead have to wait for the `RxAckTimeout` TX-abort (which esp-radio
    // does not report either). Leaving it off means TX-done fires as soon as
    // the frame is out; incoming ACK frames are aborted by the hardware with
    // `RxAbortReason::UnexpectedAck`, which `ensure_receive_enabled()` recovers
    // from on the next poll.
    cfg.auto_ack_rx = false;
    // 802.15.4-2015 enhanced ACKs are not used by Zigbee PRO and esp-radio has
    // no enh-ack generator, so leaving this on would stall the RX state
    // machine on any 2015-version frame.
    cfg.enhance_ack_tx = false;
    cfg.coordinator = false;
    // Let the ISR put the radio straight back into RX after every RX, TX and
    // auto-ACK. Without this the radio parks in idle and stays deaf until
    // software re-arms it — and software re-arming is exactly what destroys
    // in-flight ACKs (see `start_receive()`).
    cfg.rx_when_idle = true;
    // A Zigbee network floods link-status/route broadcasts; esp-radio's default
    // of 10 queued frames overflows ("Receive queue full") while the MAC is
    // busy with a TX burst or a flash write.
    cfg.rx_queue_size = cfg.rx_queue_size.max(20);
}

/// Return the sequence number if `rx` is an IEEE 802.15.4 ACK frame.
fn ack_sequence(rx: &RxFrame) -> Option<u8> {
    crate::frames::ack_sequence(&rx.data[..rx.len])
}
