[package]
name = "mock-sleepy-sensor"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "mock-sleepy-sensor"
path = "src/main.rs"

[dependencies]
sensor-sed-app = { path = "../../apps/sensor-sed" }
zigbee-aps = { path = "../../zigbee-aps" }
zigbee-mac = { path = "../../zigbee-mac", features = ["mock"] }
zigbee-runtime = { path = "../../zigbee-runtime", default-features = false }
zigbee-types = { path = "../../zigbee-types" }
zigbee-zcl = { path = "../../zigbee-zcl", default-features = false }
pollster = "0.4"
