[package]
name = "mock-coordinator"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "mock-coordinator"
path = "src/main.rs"

[dependencies]
router-app = { path = "../../apps/router", features = ["router"] }
zigbee-aps = { path = "../../zigbee-aps" }
zigbee-mac = { path = "../../zigbee-mac", features = ["mock"] }
zigbee-runtime = { path = "../../zigbee-runtime", default-features = false, features = ["router"] }
zigbee-types = { path = "../../zigbee-types" }
zigbee-zcl = { path = "../../zigbee-zcl", default-features = false }
pollster = "0.4"
